
export const romanianCities: string[] = [
  "București",
  "Cluj-Napoca",
  "Timișoara",
  "Iași",
  "Constanța",
  "Craiova",
  "Brașov",
  "Galați",
  "Ploiești",
  "Oradea",
  "Brăila",
  "Arad",
  "Pitești",
  "Sibiu",
  "Bacău",
  "Târgu Mureș",
  "Baia Mare",
  "Buzău",
  "Botoșani",
  "Satu Mare",
  "Râmnicu Vâlcea",
  "Suceava",
  "Piatra Neamț",
  "Drobeta-Turnu Severin",
  "Târgu Jiu",
  "Tulcea",
  "Târgoviște",
  "Focșani",
  "Bistrița",
  "Reșița",
  "Slatina",
  "Călărași",
  "Alba Iulia",
  "Giurgiu",
  "Deva",
  "Hunedoara",
  "Zalău",
  "Sfântu Gheorghe",
  "Bârlad",
  "Vaslui",
  "Roman",
  "Turda",
  "Mediaș",
  "Slobozia",
  "Alexandria",
  "Voluntari",
  "Lugoj",
  "Medgidia",
  "Onești",
  "Miercurea Ciuc",
  "Sighetu Marmației",
  "Petroșani",
  "Mangalia",
  "Tecuci",
  "Năvodari",
  "Câmpina",
  "Făgăraș",
  "Caracal",
  "Fetești",
  "Curtea de Argeș",
  "Sighișoara",
  "Dorohoi",
  "Roșiorii de Vede",
  "Turnu Măgurele",
  "Pașcani",
  "Huși",
  "Câmpulung",
  "Săcele",
  "Reghin",
  "Gherla",
  "Oltenița",
  "Aiud",
  "Sebeș",
  "Cugir",
  "Târnăveni",
  "Petrila",
  "Zărnești",
  "Codlea",
  "Rădăuți",
  "Câmpia Turzii",
  "Comănești",
  "Carei",
  "Blaj",
  "Târgu Secuiesc",
  "Moinești",
  "Odorheiu Secuiesc",
  "Lupeni",
  "Târgu Neamț",
  "Corabia",
  "Băilești",
  "Drăgășani",
  "Gheorgheni",
  "Vulcan",
  "Brad"
];
