
export const romanianCountiesWithCities: { county: string, cities: string[] }[] = [
  { county: "Alba", cities: ["Alba Iulia", "Aiud", "Blaj", "Sebeș", "Cugir", "Câmpeni", "Zlatna", "Abrud", "Ocna Mureș", "Teiuș"] },
  { county: "Arad", cities: ["Arad", "Pecica", "Sântana", "Lipova", "Ineu", "Chișineu-Criș", "Nădlac", "Curtici", "Pâncota", "Sebiș"] },
  { county: "Argeș", cities: ["Pitești", "Mioveni", "Câmpulung", "Curtea de Argeș", "Ștefănești", "Costești", "Topoloveni"] },
  { county: "Bacău", cities: ["Bacău", "Onești", "Moinești", "Comănești", "Buhuși", "Dărmănești", "Târgu Ocna", "Slănic-Moldova"] },
  { county: "Bihor", cities: ["Oradea", "Salonta", "Marghita", "Săcueni", "Beiuș", "Valea lui Mihai", "Aleșd", "Ștei", "Nucet", "Vașcău"] },
  { county: "Bistrița-Năsăud", cities: ["Bistrița", "Beclean", "Sângeorz-Băi", "Năsăud"] },
  { county: "Botoșani", cities: ["Botoșani", "Dorohoi", "Darabani", "Flămânzi", "Săveni", "Ștefănești", "Bucecea"] },
  { county: "Brașov", cities: ["Brașov", "Săcele", "Făgăraș", "Codlea", "Zărnești", "Râșnov", "Victoria", "Predeal", "Rupea", "Ghimbav"] },
  { county: "Brăila", cities: ["Brăila", "Ianca", "Însurăței", "Făurei"] },
  { county: "Buzău", cities: ["Buzău", "Râmnicu Sărat", "Nehoiu", "Pogoanele", "Pătârlagele"] },
  { county: "Caraș-Severin", cities: ["Reșița", "Caransebeș", "Bocșa", "Oravița", "Moldova Nouă", "Oțelu Roșu", "Anina", "Băile Herculane"] },
  { county: "Călărași", cities: ["Călărași", "Oltenița", "Fundulea", "Budești", "Lehliu Gară"] },
  { county: "Cluj", cities: ["Cluj-Napoca", "Turda", "Dej", "Câmpia Turzii", "Gherla", "Huedin"] },
  { county: "Constanța", cities: ["Constanța", "Medgidia", "Mangalia", "Năvodari", "Cernavodă", "Ovidiu", "Murfatlar", "Hârșova", "Eforie", "Techirghiol", "Băneasa", "Negru Vodă"] },
  { county: "Covasna", cities: ["Sfântu Gheorghe", "Târgu Secuiesc", "Covasna", "Baraolt", "Întorsura Buzăului"] },
  { county: "Dâmbovița", cities: ["Târgoviște", "Moreni", "Pucioasa", "Găești", "Titu", "Fieni", "Răcari"] },
  { county: "Dolj", cities: ["Craiova", "Băilești", "Calafat", "Filiași", "Dăbuleni", "Segarcea", "Bechet"] },
  { county: "Galați", cities: ["Galați", "Tecuci", "Târgu Bujor", "Berheci"] },
  { county: "Giurgiu", cities: ["Giurgiu", "Bolintin-Vale", "Mihăilești"] },
  { county: "Gorj", cities: ["Târgu Jiu", "Motru", "Rovinari", "Bumbești-Jiu", "Târgu Cărbunești", "Turceni", "Tismana", "Novaci", "Țicleni"] },
  { county: "Harghita", cities: ["Miercurea Ciuc", "Odorheiu Secuiesc", "Gheorgheni", "Toplița", "Cristuru Secuiesc", "Bălan", "Vlăhița", "Băile Tușnad", "Borsec"] },
  { county: "Hunedoara", cities: ["Deva", "Hunedoara", "Petroșani", "Vulcan", "Lupeni", "Petrila", "Orăștie", "Brad", "Simeria", "Călan", "Hațeg", "Uricani", "Geoagiu", "Aninoasa"] },
  { county: "Ialomița", cities: ["Slobozia", "Fetești", "Urziceni", "Țăndărei", "Amara", "Căzănești", "Fierbinți-Târg"] },
  { county: "Iași", cities: ["Iași", "Pașcani", "Târgu Frumos", "Hârlău", "Podu Iloaiei"] },
  { county: "Ilfov", cities: ["Voluntari", "Pantelimon", "Buftea", "Popești-Leordeni", "Bragadiru", "Chitila", "Otopeni", "Măgurele"] },
  { county: "Maramureș", cities: ["Baia Mare", "Sighetu Marmației", "Borșa", "Baia Sprie", "Vișeu de Sus", "Târgu Lăpuș", "Seini", "Somcuta Mare", "Ulmeni", "Tăuții-Măgherăuș", "Cavnic", "Săliștea de Sus", "Dragomirești"] },
  { county: "Mehedinți", cities: ["Drobeta-Turnu Severin", "Orșova", "Strehaia", "Vânju Mare", "Baia de Aramă"] },
  { county: "Mureș", cities: ["Târgu Mureș", "Reghin", "Sighișoara", "Târnăveni", "Luduș", "Sovata", "Iernut", "Sărmașu", "Ungheni", "Miercurea Nirajului", "Sângeorgiu de Pădure"] },
  { county: "Neamț", cities: ["Piatra Neamț", "Roman", "Târgu Neamț", "Bicaz", "Roznov"] },
  { county: "Olt", cities: ["Slatina", "Caracal", "Balș", "Corabia", "Scornicești", "Drăgănești-Olt", "Piatra-Olt", "Potcoava"] },
  { county: "Prahova", cities: ["Ploiești", "Câmpina", "Băicoi", "Breaza", "Mizil", "Comarnic", "Vălenii de Munte", "Boldești-Scăeni", "Urlați", "Sinaia", "Bușteni", "Plopeni", "Slănic", "Azuga"] },
  { county: "Satu Mare", cities: ["Satu Mare", "Carei", "Negrești-Oaș", "Tășnad", "Livada", "Ardud"] },
  { county: "Sălaj", cities: ["Zalău", "Șimleu Silvaniei", "Jibou", "Cehu Silvaniei"] },
  { county: "Sibiu", cities: ["Sibiu", "Mediaș", "Cisnădie", "Avrig", "Agnita", "Dumbrăveni", "Tălmaciu", "Copșa Mică", "Săliște", "Miercurea Sibiului", "Ocna Sibiului"] },
  { county: "Suceava", cities: ["Suceava", "Fălticeni", "Rădăuți", "Câmpulung Moldovenesc", "Vatra Dornei", "Vicovu de Sus", "Gura Humorului", "Dolhasca", "Liteni", "Salcea", "Siret", "Cajvana", "Frasin", "Broșteni", "Milișăuți", "Solca"] },
  { county: "Teleorman", cities: ["Alexandria", "Roșiorii de Vede", "Turnu Măgurele", "Zimnicea", "Videle"] },
  { county: "Timiș", cities: ["Timișoara", "Lugoj", "Sânnicolau Mare", "Jimbolia", "Recaș", "Buziaș", "Făget", "Deta", "Gătaia", "Ciacova"] },
  { county: "Tulcea", cities: ["Tulcea", "Babadag", "Măcin", "Isaccea", "Sulina"] },
  { county: "Vaslui", cities: ["Vaslui", "Bârlad", "Huși", "Negrești", "Murgeni"] },
  { county: "Vâlcea", cities: ["Râmnicu Vâlcea", "Drăgășani", "Băbeni", "Călimănești", "Horezu", "Brezoi", "Bălcești", "Berbești", "Băile Olănești", "Ocnele Mari", "Băile Govora"] },
  { county: "Vrancea", cities: ["Focșani", "Adjud", "Mărășești", "Odobești", "Panciu"] },
  { county: "București", cities: ["București"] }
];

export const romanianCities: string[] = romanianCountiesWithCities.flatMap(county => county.cities.map(city => `${city}, ${county.county}`)).sort();
