
name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck
      - name: Build
        run: npm run build
        env:
            NEXT_PUBLIC_FB_API_KEY: ${{ secrets.FB_API_KEY }}
            NEXT_PUBLIC_FB_AUTH_DOMAIN: ${{ secrets.FB_AUTH_DOMAIN }}
            NEXT_PUBLIC_FB_PROJECT_ID: ${{ secrets.FB_PROJECT_ID }}
            NEXT_PUBLIC_FB_STORAGE_BUCKET: ${{ secrets.FB_STORAGE_BUCKET }}
            NEXT_PUBLIC_FB_MESSAGING_SENDER_ID: ${{ secrets.FB_MESSAGING_SENDER_ID }}
            NEXT_PUBLIC_FB_APP_ID: ${{ secrets.FB_APP_ID }}
            NEXT_PUBLIC_FB_APPCHECK_SITE_KEY: ${{ secrets.FB_APPCHECK_SITE_KEY }}
            NEXT_PUBLIC_FB_APPCHECK_DEBUG_TOKEN: "" # Not needed for CI
      - name: Deploy to Preview Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FB_SA_KEY }}'
          projectId: '${{ secrets.FB_PROJECT_ID }}'
